import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Takeuchi Portfolio',
  description: 'Generated by create Takeuchi Portfolio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head>
        {/* ここに追加のメタタグやフォントのリンクを含めることができます */}
      </head>
      <body className={`${inter.className} bg-blue-50 text-gray-800`}>
        <Header />
        <main className="container mx-auto px-4 py-8 min-h-screen">
          {children}
        </main>
        <footer className="py-4 text-center border-t mt-8 bg-blue-200 text-blue-800">
          © 2023 Takeuchi Portfolio. All rights reserved.
        </footer>
      </body>
    </html>
  )
}
